config/routes.rb
Rails.application.routes.draw do
  root "profiles#index"
  
  resources :bits do
    collection do
      get :get_bits
    end
  end
  
  resources :profiles do
      collection do
        get :get_friend_ids
        post :add_friend
        get :get_all_profiles
        get :get_friends
        get :get_all_pending_requests
        get :get_all_friend_requests
        post :handle_friend_request
      end
    end

  devise_for :users, :controllers => { registrations: 'registrations' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bit.rb
class Bit < ApplicationRecord

  belongs_to :profile

  def self.get_all_profile_bits(id)
    bits = self.all.where(profile_id: id)
  end
end

app/controllers/bits_controller.rb
class BitsController < ApplicationController
  before_action :set_bit, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json, :xml

  # GET /bits
  # GET /bits.json
  def index
    @bits = Bit.all
  end

  # GET /bits/1
  # GET /bits/1.json
  def show
  end

  def get_bits
    id = params.keys[0].to_i
    @bits = Bit.get_all_profile_bits(id)

    respond_with(@bits.to_json)
  end

  # GET /bits/new
  def new
    @bit = Bit.new
  end

  # GET /bits/1/edit
  def edit
  end

  # POST /bits
  # POST /bits.json
  def create
    @bit = Bit.new(bit_params)

    respond_to do |format|
      if @bit.save
        format.html { redirect_to @bit, notice: 'Bit was successfully created.' }
        format.json { render :show, status: :created, location: @bit }
      else
        format.html { render :new }
        format.json { render json: @bit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bits/1
  # PATCH/PUT /bits/1.json
  def update
    respond_to do |format|
      if @bit.update(bit_params)
        format.html { redirect_to @bit, notice: 'Bit was successfully updated.' }
        format.json { render :show, status: :ok, location: @bit }
      else
        format.html { render :edit }
        format.json { render json: @bit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bits/1
  # DELETE /bits/1.json
  def destroy
    @bit.destroy
    respond_to do |format|
      format.html { redirect_to bits_url, notice: 'Bit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bit
      @bit = Bit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bit_params
      params.require(:bit).permit(:content, :profile_id, :profile_id)
    end
end

app/helpers/bits_helper.rb
module BitsHelper
end

app/views/bits/_form.html.erb
<%= form_with(model: bit, local: true) do |form| %>
  <% if bit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bit.errors.count, "error") %> prohibited this bit from being saved:</h2>

      <ul>
      <% bit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :profile_id %>
    <%= form.number_field :profile_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bits/edit.html.erb
<h1>Editing Bit</h1>

<%= render 'form', bit: @bit %>

<%= link_to 'Show', @bit %> |
<%= link_to 'Back', bits_path %>

app/views/bits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bits</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bits.each do |bit| %>
      <tr>
        <td><%= bit.content %></td>
        <td><%= bit.profile_id %></td>
        <td><%= link_to 'Show', bit %></td>
        <td><%= link_to 'Edit', edit_bit_path(bit) %></td>
        <td><%= link_to 'Destroy', bit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bit', new_bit_path %>

app/views/bits/new.html.erb
<h1>New Bit</h1>

<%= render 'form', bit: @bit %>

<%= link_to 'Back', bits_path %>

app/views/bits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @bit.content %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @bit.profile_id %>
</p>

<%= link_to 'Edit', edit_bit_path(@bit) %> |
<%= link_to 'Back', bits_path %>